apiVersion: v1
kind: ReplicationController
metadata:
  name: gocd-server
  labels:
    app: gocd-server
spec:
  replicas: 1
  selector:
    app: gocd-server
  template:
    metadata:
      labels:
        app: gocd-server
    spec:
      containers:
      - name: gocd-server
        image: tpbrown/gocd-docker:latest
        ports:
          - containerPort: 8153
          - containerPort: 8154
        resources:
          limits:
            memory: "2000Mi"
            cpu: ".5"
        livenessProbe:
          httpGet:
            path: /go/api/version
            port: 8153
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /go/api/version
            port: 8153
          initialDelaySeconds: 30
          timeoutSeconds: 5
