apiVersion: v1
kind: Service
metadata:
  name: gocd-server
  labels:
    app: gocd-server
spec:
  ports:
  - port: 8153
    targetPort: 8153
    name: port0
  - port: 8154
    targetPort: 8154
    name: port1
  selector:
    app: gocd-server
  type: NodePort
  sessionAffinity: None
